#define IDENT       1
#define FLOAT       2
#define CONST       3
#define STRING      4
#define ICOMMENT    5
#define LPAR        6
#define RPAR        7
#define SEMI        8
#define DOT         9
#define LBRACE      10
#define RBRACE      11
#define EQUAL       12
#define DQUOTE      13
#define LESS        14
#define GREATER     15
#define LBRACKET    16
#define RBRACKET    17
#define MINUS       18
#define PLUS        19
#define MUL         20
#define DIVIDE      21
#define RETURN      22
#define BCOMMENTSTART   23
#define BCOMMENTEND     24
#define ERROR           25
